name: CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Setup ${{ matrix.rust }} toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build (all features)
        run: cargo build --all-features

      - name: Build
        run: cargo build

      - name: Test (all features)
        run: cargo test --all-features

      - name: Test
        run: cargo test
